<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Title is not Same:FAIL]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="74984" started-at="2017-01-16T07:01:16Z" finished-at="2017-01-16T07:02:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="74984" started-at="2017-01-16T07:01:16Z" finished-at="2017-01-16T07:02:31Z">
      <class name="com.actitime.test.ValidLogin">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.actitime.test.ValidLogin@548a9f61]" name="preCondition" is-config="true" duration-ms="41355" started-at="2017-01-16T12:31:16Z" finished-at="2017-01-16T12:31:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="FAIL" signature="testValidLogin()[pri:0, instance:com.actitime.test.ValidLogin@548a9f61]" name="testValidLogin" duration-ms="29885" started-at="2017-01-16T12:31:57Z" finished-at="2017-01-16T12:32:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.actitime.pom.BasePage.verifyTitle(BasePage.java:36)
	at com.actitime.test.ValidLogin.testValidLogin(ValidLogin.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Title is not Same:FAIL]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method status="PASS" signature="postCondition()[pri:0, instance:com.actitime.test.ValidLogin@548a9f61]" name="postCondition" is-config="true" duration-ms="3510" started-at="2017-01-16T12:32:27Z" finished-at="2017-01-16T12:32:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- com.actitime.test.ValidLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
